apiVersion: v1
data:
  username: {{ printf "%s" .Values.rabbitmq.auth.username | b64enc }}
  password: {{ printf "%s" .Values.rabbitmq.auth.password | b64enc | quote }}
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
