apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.engine.serviceName }}
    release: {{ .Release.Name }}
  name: {{ required "Missing engine.serviceName " .Values.engine.serviceName }}
spec:
  ports:
  - port: {{ required "Missing engine.port" .Values.engine.port }}
    protocol: TCP
    targetPort: {{ .Values.engine.port }}
  selector:
    app: {{ .Values.engine.serviceName }}
    release: {{ .Release.Name }}